.PHONY: clean All

All:
	@echo "----------Building project:[ ZD_1 - Release ]----------"
	@cd "C++Projects" && "$(MAKE)" -f  "ZD_1.mk"
clean:
	@echo "----------Cleaning project:[ ZD_1 - Release ]----------"
	@cd "C++Projects" && "$(MAKE)" -f  "ZD_1.mk" clean
